const Joi = require('joi');

// Esquemas de validación para Empresa
const empresaSchema = {
  create: Joi.object({
    nombreComercial: Joi.string().max(500).required(),
    domicilioComercial: Joi.string().max(500),
    tipoPaquete: Joi.string().max(100),
    idTipoPaquete: Joi.number().integer().positive(),
    idGiroComercial: Joi.number().integer().positive(),
    precioVenta: Joi.number().precision(4).positive(),
    fechaContratacion: Joi.date(),
    diaPago: Joi.number().integer().min(1).max(31).default(1),
    diasProrroga: Joi.number().integer().min(0).max(365).default(15),
    nombreContacto: Joi.string().max(500),
    telefono: Joi.string().max(50),
    email: Joi.string().email().max(50),
    idStatus: Joi.number().integer().min(0).max(3).default(1),
    observaciones: Joi.string().max(500),
    modulosContratados: Joi.string(),
    tieneRfc: Joi.boolean().default(false),
    tieneSucursales: Joi.number().integer().min(0).max(1),
    impuestosUtilizados: Joi.string(),
    modoPruebasFactrain: Joi.boolean().default(false),
    catalogoProducto1: Joi.string().max(50),
    catalogoProductos1: Joi.string().max(50),
    catalogoProducto2: Joi.string().max(50),
    catalogoProductos2: Joi.string().max(50),
    logoBase64: Joi.string(),
    headerPdf: Joi.string().max(20),
    rgbLineasPdf: Joi.string().max(10),
    rgbRellenoPdf: Joi.string().max(10),
    rgbLetrasRellenoPdf: Joi.string().max(10),
    rgbTextoWeb: Joi.string().max(10),
    idEmisorFactrain: Joi.number().integer(),
    labels: Joi.string(),
    productosApartadosHrs: Joi.number().integer().min(0),
    tituloRecoleccionManana: Joi.string().max(250),
    tituloRecoleccionTarde: Joi.string().max(250),
    latitude: Joi.string().max(100),
    longitude: Joi.string().max(100),
    apiServers: Joi.string().max(5000),
    mercadoPagoPublicKey: Joi.string().max(100),
    mercadoPagoAccessToken: Joi.string().max(100)
  }),

  update: Joi.object({
    nombreComercial: Joi.string().max(500),
    domicilioComercial: Joi.string().max(500),
    tipoPaquete: Joi.string().max(100),
    idTipoPaquete: Joi.number().integer().positive(),
    idGiroComercial: Joi.number().integer().positive(),
    precioVenta: Joi.number().precision(4).positive(),
    fechaContratacion: Joi.date(),
    diaPago: Joi.number().integer().min(1).max(31),
    diasProrroga: Joi.number().integer().min(0).max(365),
    nombreContacto: Joi.string().max(500),
    telefono: Joi.string().max(50),
    email: Joi.string().email().max(50),
    idStatus: Joi.number().integer().min(0).max(3),
    observaciones: Joi.string().max(500),
    modulosContratados: Joi.string(),
    tieneRfc: Joi.boolean(),
    tieneSucursales: Joi.number().integer().min(0).max(1),
    impuestosUtilizados: Joi.string(),
    modoPruebasFactrain: Joi.boolean(),
    catalogoProducto1: Joi.string().max(50),
    catalogoProductos1: Joi.string().max(50),
    catalogoProducto2: Joi.string().max(50),
    catalogoProductos2: Joi.string().max(50),
    logoBase64: Joi.string(),
    headerPdf: Joi.string().max(20),
    rgbLineasPdf: Joi.string().max(10),
    rgbRellenoPdf: Joi.string().max(10),
    rgbLetrasRellenoPdf: Joi.string().max(10),
    rgbTextoWeb: Joi.string().max(10),
    idEmisorFactrain: Joi.number().integer(),
    labels: Joi.string(),
    productosApartadosHrs: Joi.number().integer().min(0),
    tituloRecoleccionManana: Joi.string().max(250),
    tituloRecoleccionTarde: Joi.string().max(250),
    latitude: Joi.string().max(100),
    longitude: Joi.string().max(100),
    apiServers: Joi.string().max(5000),
    mercadoPagoPublicKey: Joi.string().max(100),
    mercadoPagoAccessToken: Joi.string().max(100)
  })
};

// Esquemas de validación para Usuario
const usuarioSchema = {
  create: Joi.object({
    idEmpresa: Joi.number().integer().positive(),
    idSucursal: Joi.number().integer().positive().default(1),
    username: Joi.string().max(50).required(),
    password: Joi.string().min(6).max(60).required(),
    nombre: Joi.string().max(100),
    apellidos: Joi.string().max(200),
    celular: Joi.string().max(50),
    email: Joi.string().email().max(200),
    idRol: Joi.number().integer().min(1).max(255).default(1),
    autorizarDescuento: Joi.number().integer().min(0).max(1).default(0),
    autorizarCorte: Joi.number().integer().min(0).max(1).default(0),
    visualSetting: Joi.string(),
    isInicializado: Joi.number().integer().min(0).max(1).default(1),
    idStatus: Joi.number().integer().min(0).max(255).default(1),
    idTarjetaPresentacion: Joi.number().integer().positive(),
    idGrado: Joi.number().integer().positive(),
    idCrmNotificacionType: Joi.number().integer().min(0).max(255),
    idCrmCalendar: Joi.string().max(200),
    crmCalendarAccessToken: Joi.string().max(500),
    crmCalendarRefreshToken: Joi.string().max(500),
    crmCalendarTokenExpiry: Joi.date(),
    crmGoogleToken: Joi.string().max(4000)
  }),

  update: Joi.object({
    idEmpresa: Joi.number().integer().positive(),
    idSucursal: Joi.number().integer().positive(),
    username: Joi.string().max(50),
    password: Joi.string().min(6).max(60),
    nombre: Joi.string().max(100),
    apellidos: Joi.string().max(200),
    celular: Joi.string().max(50),
    email: Joi.string().email().max(200),
    idRol: Joi.number().integer().min(1).max(255),
    autorizarDescuento: Joi.number().integer().min(0).max(1),
    autorizarCorte: Joi.number().integer().min(0).max(1),
    visualSetting: Joi.string(),
    isInicializado: Joi.number().integer().min(0).max(1),
    idStatus: Joi.number().integer().min(0).max(255),
    idTarjetaPresentacion: Joi.number().integer().positive(),
    idGrado: Joi.number().integer().positive(),
    idCrmNotificacionType: Joi.number().integer().min(0).max(255),
    idCrmCalendar: Joi.string().max(200),
    crmCalendarAccessToken: Joi.string().max(500),
    crmCalendarRefreshToken: Joi.string().max(500),
    crmCalendarTokenExpiry: Joi.date(),
    crmGoogleToken: Joi.string().max(4000)
  })
};

// Esquemas de validación para Producto
const productoSchema = {
  create: Joi.object({
    idProductoTipo: Joi.number().integer().positive(),
    idEmpresa: Joi.number().integer().positive(),
    idSucursal: Joi.number().integer().positive(),
    idLaboratorio: Joi.number().integer().positive(),
    idProveedor: Joi.number().integer().positive(),
    idEstatus: Joi.number().integer().min(0).max(255).default(1),
    isRenta: Joi.number().integer().min(0).max(1).default(0),
    isComplementoExtra: Joi.number().integer().min(0).max(1).default(0),
    codigo: Joi.string().max(30).required(),
    codigoProducto: Joi.string().max(30).allow(null).optional(),
    claveProveedor: Joi.string().max(30).allow(null).optional(),
    claveInterna: Joi.string().max(30).allow(null).optional().default(''),
    nombre: Joi.string().max(200).required(),
    slug: Joi.string().max(150).required(),
    descripcion: Joi.string().max(5000).required(),
    especificaciones: Joi.string(),
    detalleEnvio: Joi.string(),
    detalleDevolucion: Joi.string(),
    peso: Joi.number().precision(4).positive(),
    largo: Joi.number().precision(4).positive(),
    ancho: Joi.number().precision(4).positive(),
    alto: Joi.number().precision(4).positive(),
    costoCaptura: Joi.number().precision(2).positive(),
    costo: Joi.number().precision(2).positive(),
    precio: Joi.number().precision(2).positive(),
    codigoProveedor: Joi.string().max(30),
    relevancia: Joi.number().integer().positive(),
    claveProdSAT: Joi.string().max(10),
    claveUnidadSAT: Joi.string().max(5),
    claveCabms: Joi.string().max(10),
    costoIncluyeIva: Joi.number().integer().min(0).max(1).default(1),
    idTasaCuotaIva: Joi.number().integer().min(0).max(255).default(2),
    costoIncluyeIeps: Joi.number().integer().min(0).max(1).default(0),
    idTasaCuotaIeps: Joi.number().integer().min(0).max(255),
    publicadoPorMarketplace: Joi.number().integer().min(0).max(1).default(1),
    visibleInEcomerce: Joi.number().integer().min(0).max(1).default(1),
    duracionMin: Joi.number().integer().min(1).max(255).default(60),
    cuentaConInventario: Joi.number().integer().min(0).max(1).default(1),
    isBajoPedido: Joi.number().integer().min(0).max(1).default(0),
    tiempoProduccion: Joi.number().integer().min(0).max(255),
    capacidadProduccion: Joi.number().integer().min(0).max(255),
    variacionesConControlPrecio: Joi.string(),
    variacionesConControlCantidad: Joi.string(),
    precioLista: Joi.number().precision(4).positive(),
    tipoComision: Joi.string().max(20),
    productoComision: Joi.number().precision(4).positive(),
    productoComisionPorcentaje: Joi.number().integer().min(0).max(255),
    rutaPlantillaDocumento: Joi.string().max(500),
    idProductoCopia: Joi.number().integer(),
    cantidad: Joi.number().precision(2).positive(),
    idAreaProduccion: Joi.number().integer().positive(),
    isPieza: Joi.number().integer().min(0).max(1).default(1),
    unidadMedida: Joi.string().max(15),
    compraIsPieza: Joi.number().integer().min(0).max(1).default(1),
    compraUnidadMedida: Joi.string().max(20),
    compraCantidad: Joi.number().integer().positive(),
    idProductoPadre: Joi.number().integer(),
    idProductoVariacion: Joi.number().integer(),
    precios: Joi.array().items(
      Joi.object({
        idEmpresa: Joi.number().integer().positive().optional(),
        idSucursal: Joi.number().integer().positive().optional(),
        nivelSocioeconomicoId: Joi.number().integer().positive().optional(),
        idUnidadMedidaOpcion: Joi.number().integer().positive().optional(),
        precioAntesImpuestos: Joi.number().precision(4).optional(),
        iva: Joi.number().precision(4).optional(),
        ieps: Joi.number().precision(4).optional(),
        precio: Joi.number().precision(4).optional(),
        cantidadDe: Joi.number().integer().optional(),
        cantidadA: Joi.number().integer().optional(),
      })
    ).optional(),
    inventario: Joi.array().items(
      Joi.object({
        idSucursal: Joi.number().integer().positive().optional(),
        idAlmacen: Joi.number().integer().positive().optional(),
        idUbicacion: Joi.number().integer().positive().optional(),
        cantidad: Joi.number().precision(2).optional(),
        stockMinimo: Joi.number().integer().optional(),
        stockMaximo: Joi.number().integer().optional(),
      })
    ).optional(),
  }),

  update: Joi.object({
    idProducto: Joi.number().integer().positive(),
    idProductoTipo: Joi.number().integer().positive(),
    idEmpresa: Joi.number().integer().positive(),
    idSucursal: Joi.number().integer().positive(),
    idLaboratorio: Joi.number().integer().positive(),
    idProveedor: Joi.number().integer().positive(),
    idEstatus: Joi.number().integer().min(0).max(255).default(1),
    isRenta: Joi.number().integer().min(0).max(1).default(0),
    isComplementoExtra: Joi.number().integer().min(0).max(1).default(0),
    codigo: Joi.string().max(30).required(),
    codigoProducto: Joi.string().max(30).allow(null).optional(),
    claveProveedor: Joi.string().max(30).allow(null).optional(),
    claveInterna: Joi.string().max(30).allow(null).allow('').default(''),
    nombre: Joi.string().max(200).required(),
    slug: Joi.string().max(150).default(''),
    descripcion: Joi.string().max(5000).default(''),
    especificaciones: Joi.string().allow(null).optional(),
    detalleEnvio: Joi.string().allow(null).optional(),
    detalleDevolucion: Joi.string().allow(null).optional(),
    peso: Joi.number().precision(4).allow(null).positive(),
    largo: Joi.number().precision(4).allow(null).positive(),
    ancho: Joi.number().precision(4).allow(null).positive(),
    alto: Joi.number().precision(4).allow(null).positive(),
    costoCaptura: Joi.number().precision(2).allow(null).positive(),
    costo: Joi.number().precision(2).positive(),
    precio: Joi.number().precision(2).positive(),
    codigoProveedor: Joi.string().max(30).allow(null).allow('').optional(),
    relevancia: Joi.number().integer().positive(),
    claveProdSAT: Joi.string().max(10).allow(null).allow('').optional(),
    claveUnidadSAT: Joi.string().max(5).allow(null).allow('').optional(),
    claveCabms: Joi.string().max(10).allow(null).allow('').optional(),
    costoIncluyeIva: Joi.number().integer().min(0).max(1),
    idTasaCuotaIva: Joi.number().integer().min(0).max(255),
    costoIncluyeIeps: Joi.number().integer().min(0).max(1),
    idTasaCuotaIeps: Joi.number().integer().min(0).max(255).allow(null).optional(),
    publicadoPorMarketplace: Joi.number().integer().min(0).max(1),
    visibleInEcomerce: Joi.number().integer().min(0).max(1),
    duracionMin: Joi.number().integer().min(1).max(255),
    cuentaConInventario: Joi.number().integer().min(0).max(1),
    isBajoPedido: Joi.number().integer().min(0).max(1),
    tiempoProduccion: Joi.number().integer().min(0).max(255).allow(null).optional(),
    capacidadProduccion: Joi.number().integer().min(0).max(255).allow(null).optional(),
    variacionesConControlPrecio: Joi.string().allow(null).optional(),
    variacionesConControlCantidad: Joi.string().allow(null).optional(),
    precioLista: Joi.number().precision(4).positive().allow(null).optional(),
    tipoComision: Joi.string().max(20).allow(null).optional(),
    productoComision: Joi.number().precision(4).positive().allow(null).optional(),
    productoComisionPorcentaje: Joi.number().integer().min(0).max(255).allow(null).optional(),
    rutaPlantillaDocumento: Joi.string().max(500).allow(null).optional(),
    idProductoCopia: Joi.number().integer().allow(null).optional(),
    cantidad: Joi.number().precision(2).positive().allow(null).allow(0).optional(),
    idAreaProduccion: Joi.number().integer().positive().allow(null).optional(),
    isPieza: Joi.number().integer().min(0).max(1),
    unidadMedida: Joi.string().max(15).allow(null).optional(),
    compraIsPieza: Joi.number().integer().min(0).max(1),
    compraUnidadMedida: Joi.string().max(20).allow(null).optional(),
    compraCantidad: Joi.number().integer().positive().allow(null).optional(),
    idProductoPadre: Joi.number().integer().allow(null).optional(),
    idProductoVariacion: Joi.number().integer().allow(null).optional(),
    empresa: Joi.object({
    
      id: Joi.number().integer().positive().optional(),
      nombreComercial: Joi.string().max(30).allow(null).optional(),
      domicilioComercial: Joi.string().max(30).allow(null).optional(),
    
    }),
    precios: Joi.array().items(
      Joi.object({
        id: Joi.number().integer().positive().optional(),
        idEmpresa: Joi.number().integer().positive().optional(),
        idProducto: Joi.number().integer().positive().optional(),
        idSucursal: Joi.number().integer().positive().optional(),
        nivelSocioeconomicoId: Joi.number().integer().positive().optional(),
        idUnidadMedidaOpcion: Joi.number().integer().positive().allow(null).optional(),
        precioAntesImpuestos: Joi.number().precision(4).optional(),
        iva: Joi.number().precision(4).optional(),
        ieps: Joi.number().precision(4).optional(),
        precio: Joi.number().precision(4).optional(),
        cantidadDe: Joi.number().integer().allow(null).optional(),
        cantidadA: Joi.number().integer().allow(null).optional(),
        createdAt: Joi.date().optional(),
        updatedAt: Joi.date().optional(),
      })
    ).optional(),
    inventario: Joi.array().items(
      Joi.object({
        id: Joi.number().integer().positive().optional(),
        idProducto: Joi.number().integer().positive().allow(null).optional(),
        idSucursal: Joi.number().integer().positive().optional(),
        idAlmacen: Joi.number().integer().positive().allow(null).optional(),
        idUbicacion: Joi.number().integer().positive().allow(null).optional(),
        cantidad: Joi.number().precision(2).optional(),
        stockMinimo: Joi.number().integer().optional(),
        stockMaximo: Joi.number().integer().allow(null).optional(),
        createdAt: Joi.date().optional(),
        updatedAt: Joi.date().optional(),

      })
    ).optional(),
    createdAt: Joi.date().optional(),
    updatedAt: Joi.date().optional(),

  })
};

// Esquemas de paginación
const paginationSchema = Joi.object({
  page: Joi.number().integer().min(1).default(1),
  limit: Joi.number().integer().min(1).default(10),
  sortBy: Joi.string(),
  sortOrder: Joi.string().valid('asc', 'desc').default('asc'),
  search: Joi.string().max(100)
});

module.exports = {
  empresaSchema,
  usuarioSchema,
  productoSchema,
  paginationSchema
}; 